# role tasks
- block:
  - name: Copy rpm files to remote
    copy:
      src: "{{ item }}"
      dest: /root
    with_items:
      - ../files/python-ptyprocess-0.5.1-2.mga7.noarch.rpm
      - ../files/python-pexpect-4.0.1-4.mga7.noarch.rpm

  - name: Install packages
    package:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - /root/python-ptyprocess-0.5.1-2.mga7.noarch.rpm
        - /root/python-pexpect-4.0.1-4.mga7.noarch.rpm
        - "{{ rhv_answerfile_engine_setup_package }}"
    notify:
      - Use default values

  - name: Render answerfile template
    template:
      src: "{{ rhv_answerfile_engine_setup_template_path }}"
      dest: /root/answerfile.txt
    notify:
      - Use answerfile
    when: not rhv_answerfile_engine_setup_use_defaults
  become: true
  become_user: "{{ rhv_answerfile_engine_setup_become_user }}"
