- name: converge
  hosts: all
  tasks:
    - name: Copy rpm files to remote
      copy:
        src: "{{ item }}"
        dest: /root
      with_items:
        - ../../files/python-ptyprocess-0.5.1-2.mga7.noarch.rpm
        - ../../files/python-pexpect-4.0.1-4.mga7.noarch.rpm
      become: true
      become_user: root

    - name: Install dependencies for ansible expect module
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - /root/python-ptyprocess-0.5.1-2.mga7.noarch.rpm
          - /root/python-pexpect-4.0.1-4.mga7.noarch.rpm
      become: true
      become_user: root
